spring:
  application:
    name: thymeleaf
  profiles:
    #    active: prod
    active: dev,app,db
    #  thymeleaf:
    # 개발 환경에서는 false (바로 반영되게)
#    cache: false
#    prefix: classpath:/templates/
#    suffix: .html

# 문서 분리
---
# 개발환경에서만 사용
server:
  #  port: 8081
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  thymeleaf:
    cache: false